/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aldisued.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PizzaOrderShop extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8593323920500648938L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PizzaOrderShop\",\"namespace\":\"com.aldisued.avro\",\"fields\":[{\"name\":\"shop\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PizzaOrderShop> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PizzaOrderShop> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PizzaOrderShop> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PizzaOrderShop> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PizzaOrderShop> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PizzaOrderShop to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PizzaOrderShop from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PizzaOrderShop instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PizzaOrderShop fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String shop;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PizzaOrderShop() {}

  /**
   * All-args constructor.
   * @param shop The new value for shop
   */
  public PizzaOrderShop(java.lang.String shop) {
    this.shop = shop;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shop;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shop = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'shop' field.
   * @return The value of the 'shop' field.
   */
  public java.lang.String getShop() {
    return shop;
  }


  /**
   * Sets the value of the 'shop' field.
   * @param value the value to set.
   */
  public void setShop(java.lang.String value) {
    this.shop = value;
  }

  /**
   * Creates a new PizzaOrderShop RecordBuilder.
   * @return A new PizzaOrderShop RecordBuilder
   */
  public static com.aldisued.avro.PizzaOrderShop.Builder newBuilder() {
    return new com.aldisued.avro.PizzaOrderShop.Builder();
  }

  /**
   * Creates a new PizzaOrderShop RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PizzaOrderShop RecordBuilder
   */
  public static com.aldisued.avro.PizzaOrderShop.Builder newBuilder(com.aldisued.avro.PizzaOrderShop.Builder other) {
    if (other == null) {
      return new com.aldisued.avro.PizzaOrderShop.Builder();
    } else {
      return new com.aldisued.avro.PizzaOrderShop.Builder(other);
    }
  }

  /**
   * Creates a new PizzaOrderShop RecordBuilder by copying an existing PizzaOrderShop instance.
   * @param other The existing instance to copy.
   * @return A new PizzaOrderShop RecordBuilder
   */
  public static com.aldisued.avro.PizzaOrderShop.Builder newBuilder(com.aldisued.avro.PizzaOrderShop other) {
    if (other == null) {
      return new com.aldisued.avro.PizzaOrderShop.Builder();
    } else {
      return new com.aldisued.avro.PizzaOrderShop.Builder(other);
    }
  }

  /**
   * RecordBuilder for PizzaOrderShop instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PizzaOrderShop>
    implements org.apache.avro.data.RecordBuilder<PizzaOrderShop> {

    private java.lang.String shop;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.aldisued.avro.PizzaOrderShop.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shop)) {
        this.shop = data().deepCopy(fields()[0].schema(), other.shop);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing PizzaOrderShop instance
     * @param other The existing instance to copy.
     */
    private Builder(com.aldisued.avro.PizzaOrderShop other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.shop)) {
        this.shop = data().deepCopy(fields()[0].schema(), other.shop);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'shop' field.
      * @return The value.
      */
    public java.lang.String getShop() {
      return shop;
    }


    /**
      * Sets the value of the 'shop' field.
      * @param value The value of 'shop'.
      * @return This builder.
      */
    public com.aldisued.avro.PizzaOrderShop.Builder setShop(java.lang.String value) {
      validate(fields()[0], value);
      this.shop = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'shop' field has been set.
      * @return True if the 'shop' field has been set, false otherwise.
      */
    public boolean hasShop() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'shop' field.
      * @return This builder.
      */
    public com.aldisued.avro.PizzaOrderShop.Builder clearShop() {
      shop = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PizzaOrderShop build() {
      try {
        PizzaOrderShop record = new PizzaOrderShop();
        record.shop = fieldSetFlags()[0] ? this.shop : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PizzaOrderShop>
    WRITER$ = (org.apache.avro.io.DatumWriter<PizzaOrderShop>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PizzaOrderShop>
    READER$ = (org.apache.avro.io.DatumReader<PizzaOrderShop>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.shop);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.shop = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.shop = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










