/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aldisued.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PizzaShopRevenue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 973888849993816845L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PizzaShopRevenue\",\"namespace\":\"com.aldisued.avro\",\"fields\":[{\"name\":\"shop\",\"type\":\"string\"},{\"name\":\"revenue\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PizzaShopRevenue> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PizzaShopRevenue> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PizzaShopRevenue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PizzaShopRevenue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PizzaShopRevenue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PizzaShopRevenue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PizzaShopRevenue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PizzaShopRevenue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PizzaShopRevenue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence shop;
  private int revenue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PizzaShopRevenue() {}

  /**
   * All-args constructor.
   * @param shop The new value for shop
   * @param revenue The new value for revenue
   */
  public PizzaShopRevenue(java.lang.CharSequence shop, java.lang.Integer revenue) {
    this.shop = shop;
    this.revenue = revenue;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shop;
    case 1: return revenue;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shop = (java.lang.CharSequence)value$; break;
    case 1: revenue = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'shop' field.
   * @return The value of the 'shop' field.
   */
  public java.lang.CharSequence getShop() {
    return shop;
  }


  /**
   * Sets the value of the 'shop' field.
   * @param value the value to set.
   */
  public void setShop(java.lang.CharSequence value) {
    this.shop = value;
  }

  /**
   * Gets the value of the 'revenue' field.
   * @return The value of the 'revenue' field.
   */
  public int getRevenue() {
    return revenue;
  }


  /**
   * Sets the value of the 'revenue' field.
   * @param value the value to set.
   */
  public void setRevenue(int value) {
    this.revenue = value;
  }

  /**
   * Creates a new PizzaShopRevenue RecordBuilder.
   * @return A new PizzaShopRevenue RecordBuilder
   */
  public static com.aldisued.avro.PizzaShopRevenue.Builder newBuilder() {
    return new com.aldisued.avro.PizzaShopRevenue.Builder();
  }

  /**
   * Creates a new PizzaShopRevenue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PizzaShopRevenue RecordBuilder
   */
  public static com.aldisued.avro.PizzaShopRevenue.Builder newBuilder(com.aldisued.avro.PizzaShopRevenue.Builder other) {
    if (other == null) {
      return new com.aldisued.avro.PizzaShopRevenue.Builder();
    } else {
      return new com.aldisued.avro.PizzaShopRevenue.Builder(other);
    }
  }

  /**
   * Creates a new PizzaShopRevenue RecordBuilder by copying an existing PizzaShopRevenue instance.
   * @param other The existing instance to copy.
   * @return A new PizzaShopRevenue RecordBuilder
   */
  public static com.aldisued.avro.PizzaShopRevenue.Builder newBuilder(com.aldisued.avro.PizzaShopRevenue other) {
    if (other == null) {
      return new com.aldisued.avro.PizzaShopRevenue.Builder();
    } else {
      return new com.aldisued.avro.PizzaShopRevenue.Builder(other);
    }
  }

  /**
   * RecordBuilder for PizzaShopRevenue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PizzaShopRevenue>
    implements org.apache.avro.data.RecordBuilder<PizzaShopRevenue> {

    private java.lang.CharSequence shop;
    private int revenue;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.aldisued.avro.PizzaShopRevenue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shop)) {
        this.shop = data().deepCopy(fields()[0].schema(), other.shop);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.revenue)) {
        this.revenue = data().deepCopy(fields()[1].schema(), other.revenue);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PizzaShopRevenue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.aldisued.avro.PizzaShopRevenue other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.shop)) {
        this.shop = data().deepCopy(fields()[0].schema(), other.shop);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.revenue)) {
        this.revenue = data().deepCopy(fields()[1].schema(), other.revenue);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'shop' field.
      * @return The value.
      */
    public java.lang.CharSequence getShop() {
      return shop;
    }


    /**
      * Sets the value of the 'shop' field.
      * @param value The value of 'shop'.
      * @return This builder.
      */
    public com.aldisued.avro.PizzaShopRevenue.Builder setShop(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.shop = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'shop' field has been set.
      * @return True if the 'shop' field has been set, false otherwise.
      */
    public boolean hasShop() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'shop' field.
      * @return This builder.
      */
    public com.aldisued.avro.PizzaShopRevenue.Builder clearShop() {
      shop = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'revenue' field.
      * @return The value.
      */
    public int getRevenue() {
      return revenue;
    }


    /**
      * Sets the value of the 'revenue' field.
      * @param value The value of 'revenue'.
      * @return This builder.
      */
    public com.aldisued.avro.PizzaShopRevenue.Builder setRevenue(int value) {
      validate(fields()[1], value);
      this.revenue = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'revenue' field has been set.
      * @return True if the 'revenue' field has been set, false otherwise.
      */
    public boolean hasRevenue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'revenue' field.
      * @return This builder.
      */
    public com.aldisued.avro.PizzaShopRevenue.Builder clearRevenue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PizzaShopRevenue build() {
      try {
        PizzaShopRevenue record = new PizzaShopRevenue();
        record.shop = fieldSetFlags()[0] ? this.shop : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.revenue = fieldSetFlags()[1] ? this.revenue : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PizzaShopRevenue>
    WRITER$ = (org.apache.avro.io.DatumWriter<PizzaShopRevenue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PizzaShopRevenue>
    READER$ = (org.apache.avro.io.DatumReader<PizzaShopRevenue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.shop);

    out.writeInt(this.revenue);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.shop = in.readString(this.shop instanceof Utf8 ? (Utf8)this.shop : null);

      this.revenue = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.shop = in.readString(this.shop instanceof Utf8 ? (Utf8)this.shop : null);
          break;

        case 1:
          this.revenue = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










