/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aldisued.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Pizza extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3622812139202703667L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Pizza\",\"namespace\":\"com.aldisued.avro\",\"fields\":[{\"name\":\"pizzaName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"additionalToppings\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},{\"name\":\"price\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Pizza> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Pizza> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Pizza> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Pizza> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Pizza> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Pizza to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Pizza from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Pizza instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Pizza fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String pizzaName;
  private java.util.List<java.lang.String> additionalToppings;
  private int price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Pizza() {}

  /**
   * All-args constructor.
   * @param pizzaName The new value for pizzaName
   * @param additionalToppings The new value for additionalToppings
   * @param price The new value for price
   */
  public Pizza(java.lang.String pizzaName, java.util.List<java.lang.String> additionalToppings, java.lang.Integer price) {
    this.pizzaName = pizzaName;
    this.additionalToppings = additionalToppings;
    this.price = price;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pizzaName;
    case 1: return additionalToppings;
    case 2: return price;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pizzaName = value$ != null ? value$.toString() : null; break;
    case 1: additionalToppings = (java.util.List<java.lang.String>)value$; break;
    case 2: price = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'pizzaName' field.
   * @return The value of the 'pizzaName' field.
   */
  public java.lang.String getPizzaName() {
    return pizzaName;
  }


  /**
   * Sets the value of the 'pizzaName' field.
   * @param value the value to set.
   */
  public void setPizzaName(java.lang.String value) {
    this.pizzaName = value;
  }

  /**
   * Gets the value of the 'additionalToppings' field.
   * @return The value of the 'additionalToppings' field.
   */
  public java.util.List<java.lang.String> getAdditionalToppings() {
    return additionalToppings;
  }


  /**
   * Sets the value of the 'additionalToppings' field.
   * @param value the value to set.
   */
  public void setAdditionalToppings(java.util.List<java.lang.String> value) {
    this.additionalToppings = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public int getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(int value) {
    this.price = value;
  }

  /**
   * Creates a new Pizza RecordBuilder.
   * @return A new Pizza RecordBuilder
   */
  public static com.aldisued.avro.Pizza.Builder newBuilder() {
    return new com.aldisued.avro.Pizza.Builder();
  }

  /**
   * Creates a new Pizza RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Pizza RecordBuilder
   */
  public static com.aldisued.avro.Pizza.Builder newBuilder(com.aldisued.avro.Pizza.Builder other) {
    if (other == null) {
      return new com.aldisued.avro.Pizza.Builder();
    } else {
      return new com.aldisued.avro.Pizza.Builder(other);
    }
  }

  /**
   * Creates a new Pizza RecordBuilder by copying an existing Pizza instance.
   * @param other The existing instance to copy.
   * @return A new Pizza RecordBuilder
   */
  public static com.aldisued.avro.Pizza.Builder newBuilder(com.aldisued.avro.Pizza other) {
    if (other == null) {
      return new com.aldisued.avro.Pizza.Builder();
    } else {
      return new com.aldisued.avro.Pizza.Builder(other);
    }
  }

  /**
   * RecordBuilder for Pizza instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Pizza>
    implements org.apache.avro.data.RecordBuilder<Pizza> {

    private java.lang.String pizzaName;
    private java.util.List<java.lang.String> additionalToppings;
    private int price;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.aldisued.avro.Pizza.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pizzaName)) {
        this.pizzaName = data().deepCopy(fields()[0].schema(), other.pizzaName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.additionalToppings)) {
        this.additionalToppings = data().deepCopy(fields()[1].schema(), other.additionalToppings);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Pizza instance
     * @param other The existing instance to copy.
     */
    private Builder(com.aldisued.avro.Pizza other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.pizzaName)) {
        this.pizzaName = data().deepCopy(fields()[0].schema(), other.pizzaName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.additionalToppings)) {
        this.additionalToppings = data().deepCopy(fields()[1].schema(), other.additionalToppings);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'pizzaName' field.
      * @return The value.
      */
    public java.lang.String getPizzaName() {
      return pizzaName;
    }


    /**
      * Sets the value of the 'pizzaName' field.
      * @param value The value of 'pizzaName'.
      * @return This builder.
      */
    public com.aldisued.avro.Pizza.Builder setPizzaName(java.lang.String value) {
      validate(fields()[0], value);
      this.pizzaName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pizzaName' field has been set.
      * @return True if the 'pizzaName' field has been set, false otherwise.
      */
    public boolean hasPizzaName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pizzaName' field.
      * @return This builder.
      */
    public com.aldisued.avro.Pizza.Builder clearPizzaName() {
      pizzaName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'additionalToppings' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getAdditionalToppings() {
      return additionalToppings;
    }


    /**
      * Sets the value of the 'additionalToppings' field.
      * @param value The value of 'additionalToppings'.
      * @return This builder.
      */
    public com.aldisued.avro.Pizza.Builder setAdditionalToppings(java.util.List<java.lang.String> value) {
      validate(fields()[1], value);
      this.additionalToppings = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'additionalToppings' field has been set.
      * @return True if the 'additionalToppings' field has been set, false otherwise.
      */
    public boolean hasAdditionalToppings() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'additionalToppings' field.
      * @return This builder.
      */
    public com.aldisued.avro.Pizza.Builder clearAdditionalToppings() {
      additionalToppings = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public int getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.aldisued.avro.Pizza.Builder setPrice(int value) {
      validate(fields()[2], value);
      this.price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.aldisued.avro.Pizza.Builder clearPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Pizza build() {
      try {
        Pizza record = new Pizza();
        record.pizzaName = fieldSetFlags()[0] ? this.pizzaName : (java.lang.String) defaultValue(fields()[0]);
        record.additionalToppings = fieldSetFlags()[1] ? this.additionalToppings : (java.util.List<java.lang.String>) defaultValue(fields()[1]);
        record.price = fieldSetFlags()[2] ? this.price : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Pizza>
    WRITER$ = (org.apache.avro.io.DatumWriter<Pizza>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Pizza>
    READER$ = (org.apache.avro.io.DatumReader<Pizza>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.pizzaName);

    if (this.additionalToppings == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.additionalToppings.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.lang.String e0: this.additionalToppings) {
        actualSize0++;
        out.startItem();
        out.writeString(e0);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    out.writeInt(this.price);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.pizzaName = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.additionalToppings = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<java.lang.String> a0 = this.additionalToppings;
        if (a0 == null) {
          a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("additionalToppings").schema().getTypes().get(1));
          this.additionalToppings = a0;
        } else a0.clear();
        SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
            e0 = in.readString();
            a0.add(e0);
          }
        }
      }

      this.price = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.pizzaName = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.additionalToppings = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.String> a0 = this.additionalToppings;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("additionalToppings").schema().getTypes().get(1));
              this.additionalToppings = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
                e0 = in.readString();
                a0.add(e0);
              }
            }
          }
          break;

        case 2:
          this.price = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










